export const CREATE_EMPLOYEE="CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const GET_ALL_EMPLOYEE="GET_ALL_EMPLOYEE";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const DELETE_ALL_EMPLOYEE="DELETE_ALL_EMPLOYEE";
export const EMPLOYEE_LOADING="EMPLOYEE_LOADING";
export const GET_ALL_QUALIFICATION_LIST="GET_ALL_QUALIFICATION_LIST";
export const GET_EMPLOYEE_BY_ID="GET_EMPLOYEE_BY_ID";
export const GET_QUALIFICATION_NAME_BY_ID="GET_QUALIFICATION_NAME_BY_ID";


